load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "adapters",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_name = "repo_sandbox_adapters",
    deps = all_crate_deps(normal = True) + ["//crates/core:core"],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "adapters_test",
    crate = ":adapters",
)
