filegroup(
    name = "catalog",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "rust-bazel-dockerfile",
    srcs = ["rust-bazel/context/Dockerfile"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "component-dockerfiles",
    srcs = glob(["components/*/context/Dockerfile"]),
    visibility = ["//visibility:public"],
)
